In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from joblib import dump
%matplotlib inline

In [2]:
df = pd.read_csv('IBM HR Employee Attrition.csv')

In [3]:
df_data_analysis = df.copy()

In [4]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [6]:
df['Attrition'] = df['Attrition'].map({'Yes': 1, 'No': 0})
df['BusinessTravel'] = df['BusinessTravel'].map({'Travel_Rarely': 0, 'Travel_Frequently': 1, 'Non-Travel': 2})
df['Department'] = df['Department'].map({'Sales': 0, 'Research & Development': 1, 'Human Resources': 2})
df['Gender'] = df['Gender'].map({'Female': 0, 'Male': 1})

df['EducationField'] = df['EducationField'].map({
    'Life Sciences': 0, 
    'Other': 1, 
    'Medical': 2,
    'Marketing': 3, 
    'Technical Degree': 4, 
    'Human Resources': 5
})

df['JobRole'] = df['JobRole'].map({
    'Sales Executive': 0, 
    'Research Scientist': 1, 
    'Laboratory Technician': 2,
    'Manufacturing Director': 3, 
    'Healthcare Representative': 4, 
    'Manager': 5,
    'Sales Representative': 6, 
    'Research Director': 7, 
    'Human Resources': 8
})

df['MaritalStatus'] = df['MaritalStatus'].map({
    'Single': 0, 
    'Married': 1, 
    'Divorced': 2
})

df = df.drop('Over18', axis=1)

df['OverTime'] = df['OverTime'].map({'No': 0, 'Yes': 1})

WE have to find correlation between Attrition and other columns then drop the columns that has not much impact on Attrition

In [7]:
#columns = ['Attrition',  'OverTime', 'Age', 'YearsWithCurrManager']
cm = df.corr()
#plt.figure(figsize=(8, 6))
#sns.heatmap(cm, annot=True, cmap='coolwarm')
#plt.show()

# Get correlations with 'Attrition'
attrition_corr = cm['Attrition']

# Print correlations sorted by absolute value
attrition_corr.abs().sort_values(ascending=False)

Attrition                   1.000000
OverTime                    0.246118
TotalWorkingYears           0.171063
JobLevel                    0.169105
MaritalStatus               0.162070
YearsInCurrentRole          0.160545
MonthlyIncome               0.159840
Age                         0.159205
YearsWithCurrManager        0.156199
StockOptionLevel            0.137145
YearsAtCompany              0.134392
JobInvolvement              0.130016
JobSatisfaction             0.103481
EnvironmentSatisfaction     0.103369
DistanceFromHome            0.077924
EducationField              0.075437
Department                  0.063991
WorkLifeBalance             0.063939
TrainingTimesLastYear       0.059478
DailyRate                   0.056652
RelationshipSatisfaction    0.045872
NumCompaniesWorked          0.043494
YearsSinceLastPromotion     0.033019
Education                   0.031373
Gender                      0.029453
JobRole                     0.027930
MonthlyRate                 0.015170
PercentSalaryHike           0.013478
EmployeeNumber              0.010577
HourlyRate                  0.006846
PerformanceRating           0.002889
BusinessTravel              0.000074
EmployeeCount                    NaN
StandardHours                    NaN
Name: Attrition, dtype: float64

In [8]:
attrition_corr.abs().sort_values(ascending=False).keys()

Index(['Attrition', 'OverTime', 'TotalWorkingYears', 'JobLevel',
       'MaritalStatus', 'YearsInCurrentRole', 'MonthlyIncome', 'Age',
       'YearsWithCurrManager', 'StockOptionLevel', 'YearsAtCompany',
       'JobInvolvement', 'JobSatisfaction', 'EnvironmentSatisfaction',
       'DistanceFromHome', 'EducationField', 'Department', 'WorkLifeBalance',
       'TrainingTimesLastYear', 'DailyRate', 'RelationshipSatisfaction',
       'NumCompaniesWorked', 'YearsSinceLastPromotion', 'Education', 'Gender',
       'JobRole', 'MonthlyRate', 'PercentSalaryHike', 'EmployeeNumber',
       'HourlyRate', 'PerformanceRating', 'BusinessTravel', 'EmployeeCount',
       'StandardHours'],
      dtype='object')

In [9]:
df.drop(columns=['EducationField', 'Department', 'WorkLifeBalance',
       'TrainingTimesLastYear', 'DailyRate', 'RelationshipSatisfaction',
       'NumCompaniesWorked', 'YearsSinceLastPromotion', 'Education', 'Gender',
       'JobRole', 'MonthlyRate', 'PercentSalaryHike', 'EmployeeNumber',
       'HourlyRate', 'PerformanceRating', 'BusinessTravel', 'EmployeeCount',
       'StandardHours'], inplace=True)
df_data_analysis.drop(columns=['EducationField', 'Department', 'WorkLifeBalance',
       'TrainingTimesLastYear', 'DailyRate', 'RelationshipSatisfaction',
       'NumCompaniesWorked', 'YearsSinceLastPromotion', 'Education', 'Gender',
       'JobRole', 'MonthlyRate', 'PercentSalaryHike', 'EmployeeNumber',
       'HourlyRate', 'PerformanceRating', 'BusinessTravel', 'EmployeeCount',
       'StandardHours','Over18'], inplace=True)

In [10]:
df.head()

,Age,Attrition,DistanceFromHome,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,MaritalStatus,MonthlyIncome,OverTime,StockOptionLevel,TotalWorkingYears,YearsAtCompany,YearsInCurrentRole,YearsWithCurrManager
0,41,1,1,2,3,2,4,0,5993,1,0,8,6,4,5
1,49,0,8,3,2,2,2,1,5130,0,1,10,10,7,7
2,37,1,2,4,2,1,3,0,2090,1,0,7,0,0,0
3,33,0,3,4,3,1,3,1,2909,1,0,8,8,7,0
4,27,0,2,1,3,1,2,1,3468,0,1,6,2,2,2

In [11]:
df.describe()

,Age,Attrition,DistanceFromHome,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,MaritalStatus,MonthlyIncome,OverTime,StockOptionLevel,TotalWorkingYears,YearsAtCompany,YearsInCurrentRole,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,0.161224,9.192517,2.721769,2.729932,2.063946,2.728571,0.902721,6502.931293,0.282993,0.793878,11.279592,7.008163,4.229252,4.123129
std,9.135373,0.367863,8.106864,1.093082,0.711561,1.106940,1.102846,0.730121,4707.956783,0.450606,0.852077,7.780782,6.126525,3.623137,3.568136
min,18.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1009.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,0.000000,2.000000,2.000000,2.000000,1.000000,2.000000,0.000000,2911.000000,0.000000,0.000000,6.000000,3.000000,2.000000,2.000000
50%,36.000000,0.000000,7.000000,3.000000,3.000000,2.000000,3.000000,1.000000,4919.000000,0.000000,1.000000,10.000000,5.000000,3.000000,3.000000
75%,43.000000,0.000000,14.000000,4.000000,3.000000,3.000000,4.000000,1.000000,8379.000000,1.000000,1.000000,15.000000,9.000000,7.000000,7.000000
max,60.000000,1.000000,29.000000,4.000000,4.000000,5.000000,4.000000,2.000000,19999.000000,1.000000,3.000000,40.000000,40.000000,18.000000,17.000000

In [12]:
df["Attrition"] = df.pop("Attrition")

create traning dataset and sort them by corr matrix for better visual clarity

In [13]:
df_training = df[[
    'OverTime',                     # 0.246118
    'TotalWorkingYears',            # 0.171063
    'JobLevel',                     # 0.169105
    'MaritalStatus',                # 0.162070
    'YearsInCurrentRole',           # 0.160545
    'MonthlyIncome',                # 0.159840
    'Age',                          # 0.159205
    'YearsWithCurrManager',         # 0.156199
    'StockOptionLevel',             # 0.137145
    'YearsAtCompany',               # 0.134392
    'JobInvolvement',               # 0.130016
    'JobSatisfaction',              # 0.103481
    'EnvironmentSatisfaction',       # 0.103369
    'Attrition'                    # 1.000000
]]

df_data_analysis = df[[
    'OverTime',                     # 0.246118
    'TotalWorkingYears',            # 0.171063
    'JobLevel',                     # 0.169105
    'MaritalStatus',                # 0.162070
    'YearsInCurrentRole',           # 0.160545
    'MonthlyIncome',                # 0.159840
    'Age',                          # 0.159205
    'YearsWithCurrManager',         # 0.156199
    'StockOptionLevel',             # 0.137145
    'YearsAtCompany',               # 0.134392
    'JobInvolvement',               # 0.130016
    'JobSatisfaction',              # 0.103481
    'EnvironmentSatisfaction',       # 0.103369
    'Attrition'                    # 1.000000
]]

We create two separate datasets: one in numeric format for model training and another preserving original categorical values for easier visual analysis

In [17]:
df_training

,OverTime,TotalWorkingYears,JobLevel,MaritalStatus,YearsInCurrentRole,MonthlyIncome,Age,YearsWithCurrManager,StockOptionLevel,YearsAtCompany,JobInvolvement,JobSatisfaction,EnvironmentSatisfaction,Attrition
0,1,8,2,0,4,5993,41,5,0,6,3,4,2,1
1,0,10,2,1,7,5130,49,7,1,10,2,2,3,0
2,1,7,1,0,0,2090,37,0,0,0,2,3,4,1
3,1,8,1,1,7,2909,33,0,0,8,3,3,4,0
4,0,6,1,1,2,3468,27,2,1,2,3,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,0,17,2,1,2,2571,36,3,1,5,4,4,3,0
1466,0,9,3,1,7,9991,39,7,1,7,2,1,4,0
1467,1,6,2,1,2,6142,27,3,1,6,4,2,2,0
1468,0,17,2,1,6,5390,49,8,0,9,2,2,4,0
1469,0,6,2,1,3,4404,34,2,0,4,4,3,2,0

In [15]:
df_data_analysis

,OverTime,TotalWorkingYears,JobLevel,MaritalStatus,YearsInCurrentRole,MonthlyIncome,Age,YearsWithCurrManager,StockOptionLevel,YearsAtCompany,JobInvolvement,JobSatisfaction,EnvironmentSatisfaction,Attrition
0,1,8,2,0,4,5993,41,5,0,6,3,4,2,1
1,0,10,2,1,7,5130,49,7,1,10,2,2,3,0
2,1,7,1,0,0,2090,37,0,0,0,2,3,4,1
3,1,8,1,1,7,2909,33,0,0,8,3,3,4,0
4,0,6,1,1,2,3468,27,2,1,2,3,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,0,17,2,1,2,2571,36,3,1,5,4,4,3,0
1466,0,9,3,1,7,9991,39,7,1,7,2,1,4,0
1467,1,6,2,1,2,6142,27,3,1,6,4,2,2,0
1468,0,17,2,1,6,5390,49,8,0,9,2,2,4,0
1469,0,6,2,1,3,4404,34,2,0,4,4,3,2,0

We save the datasets using Joblib (as pickle files) to avoid repeated data cleaning and enable mid-process progress saving.

In [16]:
dump(df_training, 'df_training.joblib')
dump(df_data_analysis, 'df_analysis.joblib')

['df_analysis.joblib']